FROM openjdk:11
ADD ./target/spring-boot-mysql-jpa-hibernate-0.0.1-SNAPSHOT.jar /usr/src/spring-boot-mysql-jpa-hibernate-0.0.1-SNAPSHOT.jar
WORKDIR usr/src
ENTRYPOINT ["java","-jar", "spring-boot-mysql-jpa-hibernate-0.0.1-SNAPSHOT.jar"]
